### PR TITLE
[ros2] Update maintainers

### PR DESCRIPTION
**Pull request by mabelzhang**
Signed-off-by: Mabel Zhang <mabel@openrobotics.org>

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Should you just delete move_base_msgs? Move base doesn't exist anymore and Navigation2 has no dependencies on it

**Comment by mabelzhang** [comment]
Just noticed the other PR. Will close this one.

**Comment by mabelzhang** [comment]
Actually I'll just leave out the update in that package and keep the other change.

**Comment by mikeferguson** [comment]
As a note - the ROS1 branch of this repo is still maintained by the ROS1 navigation team (@Dlu and myself). I don't think we need additional help from Open Robotics (I know you folks are spread pretty thin on a bunch of packages).

The ROS2 branch I'm not really involved in at this time - but honestly, I think @SteveMacenski and the ROS2 nav team should probably be maintainers until messages get upstreamed into nav_msgs some day and the ROS2 branch could die off.

**Comment by mabelzhang** [comment]
@SteveMacenski do you want to be added to the maintainers for `map_msgs`?

Just for context, we are adding an Open Robotics employee to all the repositories checked out in the ROS 2 core build, because we can't do a release without releasing the packages. `map_msgs` is used by `rviz_default_plugins` https://github.com/ros2/rviz/blob/ros2/rviz_default_plugins/CMakeLists.txt#L64 , so we'd like to have an OR employee on the maintainer list. I believe there's no one from OR on the ROS 2 nav team, so it'd be whoever that wants to + 1 from OR.

**Comment by SteveMacenski** [comment]
Sure, why not.

**Comment by mabelzhang** [comment]
Are we good to merge?

**Pull request merged**
