### PR TITLE
Update maintainers

### PR DESCRIPTION
**Pull request by audrow**
FYI @clalancette 

- Add Michael Jeronimo to CODEOWNERs file
- Update maintainers to Michael Jeronimo

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I don’t think this is accurate. These people still maintain this. I’m not sure Michael’s involved with anything related to Navigation unless there’s something happening at OR internally. 

Though not sure the semantic use of maintainer vs author. Or why there’s a new file only listing Michael.

**Comment by clalancette** [comment]
So what we did is to add an Open Robotics person as a maintainer for every single repository in https://github.com/ros2/ros2/blob/rolling/ros2.repos .  This is an explicit acknowledgement that all of these packages are release-critical.

That said, I agree that the previous maintainers here should be preserved.  In this case, I think we should remove Mabel, add @mjeronimo, and leave the rest as-is.  @audrow Can you make that change?

As far as CODEOWNDERS is concerned, that is just another way to note who the maintainers are which works even in the absence of a package.xml file.  The new thing with it is that you'll get explicit notifications about issues and pull requests that are opened on the repository (if you aren't already otherwise subscribed).  We don't have to do this on this repository, but again, we are doing it on all of the other repositories in ros2.repos.

**Comment by SteveMacenski** [comment]
OK all that makes sense. I'd just ask that if there's a parallel list of maintainers, it should contain all the maintainers and revert the changes to the package.xml. Adding Michael is A-OK, but don't remove others.

**Comment by audrow** [comment]
I moved Mabel to be an author and added Michael as a maintainer while leaving the other maintainers.

**Review by mjeronimo — APPROVED** [review]

**Review by clalancette — APPROVED** [review]
This looks good to me as well, but I think we should wait for an approval from @SteveMacenski before merging it in.

**Pull request merged**
