### PR TITLE
Remove move_base_msgs for Foxy and newer

### PR DESCRIPTION
**Pull request by tfoote**
Based on the pre Foxy Message API review move_base_msgs looks to be unused in ROS 2.

It's not used by the navigation2 stack. There appears to be one packages with it included in Dashing. 

https://github.com/swri-robotics/mapviz/blob/a9fae88b2aa930ccb0b53ae0d51cf5af4dc64d89/mapviz_plugins/package.xml#L28

However I think that is a pure porting effort and not necessarily indicative of useage. 

The proposal is to remove this for Foxy and newer to avoid clutter. https://github.com/ros2/common_interfaces/pull/86/files#r393333245

This is the followup ticket with that suggestion.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Agreed. In reviewing the remaining messages, it looks like a bunch of the `map_msgs` might be better rolled into `nav_msgs`. `nav_msgs` has `OccupancyGrid` but `map_msgs` has its `Update`.

**Comment by SteveMacenski** [comment]
I don't know if I "officially" maintain this repo enough to merge this, but as the Nav2 WG lead, I support it for whomever feels they have the authority to merge (@mabelzhang). Now would be a good time to merge it before G-turtle

**Comment by mabelzhang** [comment]
I don't feel I have the authority to merge since my PRs for adding myself as maintainer are still pending, and I honestly don't know the implications. Seeing this is from March though... I don't know if miracle will happen if I just sit and wait.

It actually looks like you're the only official maintainer in the ros2 branch of this repo since this change https://github.com/ros-planning/navigation_msgs/pull/10/files#r315961706

Should we tag somebody else?

**Comment by SteveMacenski** [comment]
>  I don't know if miracle will happen if I just sit and wait.

Well, if you qualify Tully or I a miracle, then yes, eventually before the end of time I believe a miracle may occur :wink: 

> It actually looks like you're the only official maintainer in the ros2 branch of this repo since this change https://github.com/ros-planning/navigation_msgs/pull/10/files#r315961706

... ok then. I'll make the executive decision to merge it. If someone's got a problem with it later we can address it. I'd rather keep things looking forward.

**Pull request merged**
