### PR TITLE
Various cleanup

### PR DESCRIPTION
**Pull request by DLu**
In prep for noetic release, this cleans up the packages and syncs the definitions to the cleaner ROS2 versions.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
LGTM

With Noetic, last one ever, how's that feel?

**Comment by mikeferguson** [comment]
We should actually create a new branch for this (rather than jade-devel) - but I'm good with all the changes after that.

**Comment by DLu** [comment]
Retargeted for new `ros1` branch.

**Review by mikeferguson — APPROVED** [review]

**Comment by mikeferguson** [comment]
Is noetic already a thing?  I see there are some very basic things in rosdistro for it already, should we be releasing this low-level set of messages already? If so, I can certainly cut a release.

**Comment by DLu** [comment]
I was on [this page](http://repositories.ros.org/status_page/blocked_source_entries_noetic.html?q=label%3D%22UNBLOCKED_BLOCKING%22&s=6&r=1) and decided to my part.

**Comment by DLu** [comment]
Well that's odd.

```
Running 'rosdep update'...
ROS Distro index file associate with commit '9861e8279e2931aed0459c01cac7c55da0f665ae'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/9861e8279e2931aed0459c01cac7c55da0f665ae/index-v4.yaml'
Could not resolve rosdep key 'actionlib_msgs'
Failed to resolve actionlib_msgs on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'actionlib_msgs', aborting.
actionlib_msgs is depended on by these packages: ['move_base_msgs']
<== Failed
Could not resolve rosdep key 'catkin'
Failed to resolve catkin on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'catkin', aborting.
catkin is depended on by these packages: ['move_base_msgs', 'map_msgs']
<== Failed
Could not resolve rosdep key 'geometry_msgs'
Failed to resolve geometry_msgs on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'geometry_msgs', aborting.
geometry_msgs is depended on by these packages: ['move_base_msgs']
<== Failed
Could not resolve rosdep key 'message_generation'
Failed to resolve message_generation on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'message_generation', aborting.
message_generation is depended on by these packages: ['move_base_msgs', 'map_msgs']
<== Failed
Could not resolve rosdep key 'message_runtime'
Failed to resolve message_runtime on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'message_runtime', aborting.
message_runtime is depended on by these packages: ['move_base_msgs', 'map_msgs']
<== Failed
Could not resolve rosdep key 'nav_msgs'
Failed to resolve nav_msgs on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'nav_msgs', aborting.
nav_msgs is depended on by these packages: ['map_msgs']
<== Failed
Could not resolve rosdep key 'sensor_msgs'
Failed to resolve sensor_msgs on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'sensor_msgs', aborting.
sensor_msgs is depended on by these packages: ['map_msgs']
<== Failed
Could not resolve rosdep key 'std_msgs'
Failed to resolve std_msgs on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'std_msgs', aborting.
std_msgs is depended on by these packages: ['map_msgs']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
You can try to address the issues which appear above and try again if you wish.
Would you like to try again? [Y/n]? 
```

**Comment by DLu** [comment]
The real problem was there are no binaries released for noetic yet, not even catkin. 

So I added the source here: https://github.com/ros/rosdistro/pull/22920

**Pull request merged**
